# Generated by Django 4.0.3 on 2022-04-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username_paswwordreset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaswwordReset',
            new_name='PasswordReset',
        ),
    ]
